[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Peripheral access API for STM32F30X microcontrollers"
documentation = "https://docs.rs/stm32f30x"
keywords = ["arm", "cortex-m", "stm32", "svd2rust"]
license = "MIT OR Apache-2.0"
name = "stm32f30x"
repository = "https://github.com/japaric/stm32f30x"
version = "0.9.0"

[dependencies]
bare-metal = "0.2.4"
cortex-m = "0.6.0"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
optional = true
version = "0.6.5"

[features]
rt = ["cortex-m-rt/device"]

[package.metadata.docs.rs]
features = ["rt"]
